# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TopasVyvoj1
                                 A QGIS plugin
 Prototyp pro vývoj částí aplikace TOPAS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-27
        copyright            : (C) 2026 by SŽ s.o., SŽG
        email                : szg@spravazeleznic.cz
        git sha              : $Format:%H$
 ***************************************************************************/

 This script initializes the plugin, making it known to QGIS.
"""

from qgis.gui import QgisInterface


# noinspection PyPep8Naming
def classFactory(iface: QgisInterface):  # pylint: disable=invalid-name
    """Load TopasVyvoj1 class from file TopasVyvoj1.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .topas_vyvoj_1 import TopasVyvoj1

    return TopasVyvoj1(iface)
