# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TopasVyvoj1Dialog
                                 A QGIS plugin
 Prototyp pro vývoj částí aplikace TOPAS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-27
        git sha              : $Format:%H$
        copyright            : (C) 2026 by SŽ s.o., SŽG
        email                : szg@spravazeleznic.cz
 ***************************************************************************/
"""

import os
from pathlib import Path

from qgis.core import (
    QgsVectorLayer,
    QgsProject,
    QgsMapLayer,
    QgsLayerTreeGroup,
)

from qgis.gui import QgisInterface
from qgis.PyQt import QtWidgets, QtCore

from .fwt import FWT
from .fwt.utility import notNone
from .zpracovani.funkce1 import SpusteniFunkce1
from .zpracovani.sql_vrstva import SqlVrstva
from .zpracovani.fme_lok import SpusteniFmeLok
from .nacteni_konfigurace import Nastaveni

# UI dialogu je kompilovaná
from .topas_vyvoj_1_dialog_base import Ui_TopasVyvoj1DialogBase


class TopasVyvoj1Dialog(QtWidgets.QDialog, Ui_TopasVyvoj1DialogBase):
    def __init__(self, iface: QgisInterface):
        """
        Kontruktor dialogu.
        """
        super(TopasVyvoj1Dialog, self).__init__(iface.mainWindow())
        self.setupUi(self)  # type: ignore[reportUnknownArgumentType]

        self.setModal(False)
        self.setWindowModality(QtCore.Qt.WindowModality.NonModal)

        self.iface = iface
        self.fwt = FWT(
            self.iface, Path(__file__).resolve().parent, max_pocet_vlaken=4
        )

        self.pbAktualizovatVrstvy.clicked.connect(
            self._on_pbAktualizovatVrstvy_clicked
        )
        self.pbAktualizovatSkupiny.clicked.connect(
            self._on_pbAktualizovatSkupiny_clicked
        )

        # Handlery akčních tlačítek
        self.pbFceSynch.clicked.connect(self._on_pbFceSynchronni_clicked)
        self.pbFceAsynch.clicked.connect(self._on_pbFceAsynchronni_clicked)
        self.pbSqlVrstaSynch.clicked.connect(self._on_pbSqlVrstaSynch_clicked)
        self.pbSqlVrstaAsynch.clicked.connect(
            self._on_pbSqlVrstaAsynch_clicked
        )

        self.pbFme2Synch.clicked.connect(self._on_pbFme2Synch_clicked)
        self.pbFme2Asynch.clicked.connect(self._on_pbFme2Asynch_clicked)
        self.pbFme3Synch.clicked.connect(self._on_pbFme3Synch_clicked)
        self.pbFme3Asynch.clicked.connect(self._on_pbFme3Asynch_clicked)

        self.pbCfgSyspath.clicked.connect(
            lambda: self._on_pbCfgSyspath_clicked(
                os.path.join(
                    self.fwt.kontext.plugin_root,
                    "config",
                    "syspaths_config.yaml",
                )
            )
        )
        self.pbCfgFME.clicked.connect(
            lambda: self._on_pbCfgSyspath_clicked(
                os.path.join(
                    self.fwt.kontext.plugin_root,
                    "config",
                    "FME_config.yaml",
                )
            )
        )
        self.pbCfgFmelog.clicked.connect(
            lambda: self._on_pbCfgSyspath_clicked(
                os.path.join(
                    self.fwt.kontext.plugin_root,
                    "fme",
                    "config_fmelog.yaml",
                )
            )
        )

        # Inicializace hodnot v UI
        self._naplnVrstvy()
        self._naplnSkupinyVrstev()

    # ----------------------------------------------------------------------

    def _on_pbAktualizovatVrstvy_clicked(self) -> None:
        self._naplnVrstvy()
        self.Vystup_1.appendPlainText("Seznam vrstev aktualizován.")

    # ----------------------------------------------------------------------

    def _on_pbAktualizovatSkupiny_clicked(self) -> None:
        self._naplnSkupinyVrstev()
        self.Vystup_1.appendPlainText("Seznam skupin aktualizován.")

    # ----------------------------------------------------------------------

    def _on_pbFceSynchronni_clicked(self) -> None:
        """
        Obsluha stisku tlačítka pro volání synchronní funkce.
        """
        SpusteniFunkce1(self.fwt, self).spustFunkci1(synchronne=True)

    # ----------------------------------------------------------------------

    def _on_pbFceAsynchronni_clicked(self) -> None:
        """
        Obsluha stisku tlačítka pro volání asynchronní funkce.
        """
        SpusteniFunkce1(self.fwt, self).spustFunkci1(synchronne=False)

    # ----------------------------------------------------------------------

    def _on_pbSqlVrstaSynch_clicked(self) -> None:
        """
        Přidání SQL vrstvy synchronní
        """
        SqlVrstva(self.fwt, self).spustVytvoreniSqlVrstvy(synchronne=True)

    # ----------------------------------------------------------------------

    def _on_pbSqlVrstaAsynch_clicked(self) -> None:
        """
        Přidání SQL vrstvy asynchronní
        """
        SqlVrstva(self.fwt, self).spustVytvoreniSqlVrstvy(synchronne=False)

    # ----------------------------------------------------------------------

    def _on_pbExportTempAll_clicked(self) -> None:
        """Export aktivní vrstvy do TEMP (vše)."""
        try:
            vrstva = notNone(self.iface.activeLayer())
            if isinstance(vrstva, QgsVectorLayer):
                self.fwt.integrace.qgis.vrstvy.zkopirujVrstvuDoTemp(
                    vrstva, "gpkg", False
                )
        except Exception as e:
            self.Vystup_1.appendPlainText(f"CHYBA exportu do TEMP (vše): {e}")

    # ----------------------------------------------------------------------

    def _on_pbExportTempSel_clicked(self) -> None:
        """Export aktivní vrstvy do TEMP (jen vybrané)."""
        try:
            vrstva = notNone(self.iface.activeLayer())
            if isinstance(vrstva, QgsVectorLayer):
                self.fwt.integrace.qgis.vrstvy.zkopirujVrstvuDoTemp(
                    vrstva, "gpkg", True
                )
        except Exception as e:
            self.Vystup_1.appendPlainText(
                f"CHYBA exportu do TEMP (jen vybrané): {e}"
            )

    # ----------------------------------------------------------------------

    def _priklad_fme(self) -> None:
        """Příklad volání FME z workflow.

        Pozn.: požadovaný příklad je záměrně volán do "nízkoúrovňové"
        integrace (ne přes workflow vrstvu).
        """
        # SpusteniPrikladFme(self).spust()

    # ----------------------------------------------------------------------

    def _on_pbFme2Synch_clicked(self) -> None:
        try:
            lokalni = self.chbLokalniFme.isChecked()
            SpusteniFmeLok(self.fwt, self).spustFme1(
                synchronne=True, lokalni=lokalni
            )
        except Exception as e:
            self.Vystup_1.appendPlainText(f"CHYBA FME 2 synch: {e}")

    # ----------------------------------------------------------------------

    def _on_pbFme2Asynch_clicked(self) -> None:
        try:
            lokalni = self.chbLokalniFme.isChecked()
            SpusteniFmeLok(self.fwt, self).spustFme1(
                synchronne=False, lokalni=lokalni
            )
        except Exception as e:
            self.Vystup_1.appendPlainText(f"CHYBA FME 2 asynch: {e}")

    # ----------------------------------------------------------------------

    def _on_pbFme3Synch_clicked(self) -> None:
        try:
            lokalni = self.chbLokalniFme.isChecked()
            SpusteniFmeLok(self.fwt, self).spustFme1(
                synchronne=True, lokalni=lokalni, qgis_layer_name="seznam chyb"
            )
        except Exception as e:
            self.Vystup_1.appendPlainText(f"CHYBA FME 3 synch: {e}")

    # ----------------------------------------------------------------------

    def _on_pbFme3Asynch_clicked(self) -> None:
        try:
            lokalni = self.chbLokalniFme.isChecked()
            SpusteniFmeLok(self.fwt, self).spustFme1(
                synchronne=False,
                lokalni=lokalni,
                qgis_layer_name="seznam chyb",
            )
        except Exception as e:
            self.Vystup_1.appendPlainText(f"CHYBA FME 3 asynch: {e}")

    def _naplnVrstvy(self) -> None:
        """Naplní Vstup_1 názvy vrstev z aktuálního projektu."""
        self.Vstup_1.clear()
        project = QgsProject.instance()
        if project is None:
            return

        vrstvy = list(project.mapLayers().values())
        vrstvy.sort(key=lambda v: v.name().lower())
        for v in vrstvy:
            if isinstance(v, QgsMapLayer):
                self.Vstup_1.addItem(v.name(), v.id())

    def _naplnSkupinyVrstev(self) -> None:
        """Naplní VstupSkupina_1 názvy skupin z vrstveného stromu."""
        self.VstupSkupina_1.clear()
        project = QgsProject.instance()
        if project is None:
            return

        root = project.layerTreeRoot()
        if root is None:
            self.VstupSkupina_1.addItem("")
            return

        skupiny: list[str] = []

        def _walk_group(group: QgsLayerTreeGroup) -> None:
            for child in group.children():
                if isinstance(child, QgsLayerTreeGroup):
                    skupiny.append(child.name())
                    _walk_group(child)

        _walk_group(root)  # type: ignore[arg-type]

        skupiny = sorted(set(skupiny), key=lambda s: s.lower())
        self.VstupSkupina_1.addItem("")
        for s in skupiny:
            self.VstupSkupina_1.addItem(s)

    # ----------------------------------------------------------------------
    def _on_pbCfgSyspath_clicked(self, conf_cesta) -> None:
        """Otevře nastavení systémové cesty (syspath) v konfiguračním souboru. - v textovém editoru."""
        try:
            Nastaveni(str(conf_cesta)).otevrit_yaml()
            self.cfglabel.setText(f"Otevřen konfigurační soubor.")
        except Exception as e:
            self.cfglabel.setText(f"CHYBA - soubor je nevalidní/neexistuje")
        
        