# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TopasVyvoj1
                                 A QGIS plugin
 Prototyp pro vývoj částí aplikace TOPAS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-01-27
        git sha              : $Format:%H$
        copyright            : (C) 2026 by SŽ s.o., SŽG
        email                : szg@spravazeleznic.cz
 ***************************************************************************/
"""
from collections.abc import Callable
from typing import Optional

from PyQt5.QtWidgets import QAction
from qgis.gui import QgisInterface
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtCore import Qt, QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon

from .fwt.utility import notNone

# Initialize Qt resources from file resources.py
from .resources import *  # noqa: F401,F403

# Import the code for the dialog
from .topas_vyvoj_1_dialog import TopasVyvoj1Dialog

import os


class TopasVyvoj1:
    """
    Implementace vývojového klienta 1 pro TOPAS jako QGIS Plugin.
    """

    _menu_uroven_1 = "&TOPAS vývojový klient 1"
    _menu_uroven_2 = "Hlavní okno vývojového klienta TOPAS 1"

    def __init__(self, iface: QgisInterface):
        """Konstruktor.

        Args:
            iface: Instance rozhraní předaná této třídě, která poskytuje
                háček, pomocí kterého lze manipulovat s aplikací QGIS za běhu.
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value("locale/userLocale")[0:2]
        locale_path = os.path.join(
            self.plugin_dir, "i18n", "TopasVyvoj1_{}.qm".format(locale)
        )

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions: list[QAction] = []
        self.menu = self.tr(TopasVyvoj1._menu_uroven_1)

        # Kontrola, zda byl plugin spuštěn poprvé v aktuální relaci QGIS
        # Musí být nastaveno v initGui(), aby přežilo znovunačtení pluginu
        self.first_start = None

    # ----------------------------------------------------------------------

    # noinspection PyMethodMayBeStatic
    def tr(self, zprava: str) -> str:
        """
        Získá překlad pro řetězec pomocí Qt translation API.
        Implementujeme si to sami, protože nedědíme z QObject.

        Args:
            zprava: Řetězec pro překlad.

        Returns:
            QString: Přeložená verze zprávy.
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate("TopasVyvoj1", zprava)

    # ----------------------------------------------------------------------

    def add_action(
        self,
        cesta_ikony: str,
        text: str,
        callback: Callable[[], None],
        povoleno: bool = True,
        pridat_do_menu: bool = True,
        pridat_do_toolbaru: bool = True,
        status_tip: Optional[str] = None,
        whats_this: Optional[str] = None,
        rodic: Optional[QtWidgets.QWidget] = None,
    ):
        """Přidá ikonu na panel nástrojů.

        Args:
            cesta_ikony: Cesta k ikoně pro tuto akci. Může být cesta ke
                zdroji (např. ':/plugins/foo/bar.png') nebo normální cesta v
                souborovém systému.
            text: Text, který se má zobrazit v položkách nabídky pro tuto
                akci.
            callback: Funkce, která se má zavolat při spuštění akce.
            povoleno: Příznak označující, zda má být akce ve výchozím
                nastavení povolena.
            pridat_do_menu: Příznak označující, zda má být akce také
                přidána do nabídky.
            pridat_do_toolbaru: Příznak označující, zda má být akce také
                přidána na panel nástrojů.
            status_tip: Volitelný text, který se zobrazí ve vyskakovacím
                okně, když se ukazatel myši vznáší nad akcí.
            whats_this: Volitelný text, který se zobrazí ve stavovém řádku,
                když se ukazatel myši vznáší nad akcí.
            rodic: Rodičovský widget pro novou akci.

        Returns:
            Vytvořená akce (a zároveň přidaná do `self.actions`).
        """

        ikona = QIcon(cesta_ikony)
        akce = QAction(ikona, text, rodic)
        akce.triggered.connect(callback)
        akce.setEnabled(povoleno)

        if status_tip is not None:
            akce.setStatusTip(status_tip)

        if whats_this is not None:
            akce.setWhatsThis(whats_this)

        if pridat_do_toolbaru:
            # Přidá ikonu pluginu na panel nástrojů Plugins
            self.iface.addToolBarIcon(akce)

        if pridat_do_menu:
            self.iface.addPluginToMenu(self.menu, akce)

        self.actions.append(akce)

        return akce

    # ----------------------------------------------------------------------

    def initGui(self):
        """Vytvoří položky nabídky a ikony panelu nástrojů v GUI QGIS."""

        cesta_ikony = ":/plugins/topas_vyvoj_1/ikona.svg"
        self.add_action(
            cesta_ikony,
            text=self.tr(TopasVyvoj1._menu_uroven_2),
            callback=self.run,
            rodic=self.iface.mainWindow(),
        )

        # bude nastaveno na False v run()
        self.first_start = True

    # ----------------------------------------------------------------------

    def unload(self):
        """Odstraní položku nabídky a ikonu pluginu z GUI QGIS."""
        for akce in self.actions:
            self.iface.removePluginMenu(
                self.tr(TopasVyvoj1._menu_uroven_1), akce
            )
            self.iface.removeToolBarIcon(akce)

    # ----------------------------------------------------------------------

    def run(self):
        """Metoda run, která provádí veškerou skutečnou práci"""

        # Vytvoření dialogu s prvky (po překladu) a uchování reference
        # GUI vytvořit POUZE JEDNOU v callbacku, aby se načetlo pouze při
        # spuštění pluginu
        if self.first_start:
            self.first_start = False
            self.dlg = TopasVyvoj1Dialog(self.iface)
            # Držet dialog nad hlavním oknem QGIS (aplikačně), ale ne jako
            # "always-on-top" přes ostatní aplikace.
            self.dlg.setParent(
                notNone(self.iface.mainWindow()),
                self.dlg.windowFlags() & ~Qt.WindowStaysOnTopHint,
            )

        # zobrazení dialogu
        self.dlg.show()

    # ----------------------------------------------------------------------
